# Generated by Django 3.1.2 on 2020-12-17 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='temp',
            new_name='temperature',
        ),
    ]
