# Generated by Django 3.1.2 on 2020-12-17 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20201217_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='added_on',
            new_name='created_on',
        ),
    ]
